baseURL = "https://gohanckz.github.io/"
languageCode = "en-us"
title = "Gohanckz Blog"
theme = "hello-friend-ng"

paginate     = 10

[params]
  dateform        = "Oct 03, 2020"
  dateformShort   = "Oct 03"
  dateformNum     = "2020-01-02"
  dateformNumTime = "2020-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Road to Red Team"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Gohanckz"
    subtitle = "Road to red team"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "# rm -rf /gohanckz"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
    
  [[menu.main]]
    identifier = "tools"
    name       = "Tools"
    url        = "/tools"

  [[menu.main]]
    identifier = "write-up"
    name       = "Write Up"
    url        = "/write-up"

  [[menu.main]]
    identifier = "whoami"
    name       = "Whoami"
    url        = "/whoami"

  [[menu.main]]
    identifier = "cheat-sheet"
    name       = "C-sheet"
    url        = "/cheat-sheet"